### ISSUE TITLE
Symbiotic does not detect memory leaks

### ISSUE THREAD

**Issue by lzaoral** [staticafi/symbiotic#132] opened 2019-12-19 16:25 UTC
Hi,
the latest builds of Symbiotic seem not to detect any memory leaks, e.g. in the code snipped below.
The same holds for more complex pieces of code. Failing build: https://copr.fedorainfracloud.org/coprs/acalabek/symbiotic/build/1129971/

```c
#include <stdlib.h>

int main(void)
{
    char* a = malloc(sizeof(char));
    a = NULL;
}
```

**Comment by mchalupa** [comment] 2020-01-04 12:50
Looks like this is caused by slicer, probably a bug in instrumentation (marking the instructions that should be kept in the program)

**Comment by mchalupa** [comment] 2020-01-07 12:54
This is a bug in dg_points_to_plugin in instrumentation when checking for possibly leaked memory. Since the allocated memory is overwritten by `NULL`, it does not appear in the state of pointer analysis at the end of `main` and is not marked as leaked. We must insert it into `possiblyLeaked` container when analysing the store instruction (this will maybe require a separate phase?)

**Closed** 2020-01-21 14:15 UTC
Labels: bug
