### ISSUE TITLE
Symbiotic can't solve sv-comp test_locks benchmarks in MemSafety-other

### ISSUE THREAD

**Issue by tomsik68** [staticafi/symbiotic#133] opened 2020-01-21 12:42 UTC
The problem is that Symbiotic can't decide memsafety of benchmarks that don't contain difficult memory-related operations. This issue is related to all sv-comp benchmarks in the following folder: https://github.com/sosy-lab/sv-benchmarks/tree/master/c/locks . 

All of the benchmarks:
+ do not use type other than `int`
+ never use the address of (`&`) nor dereference (`*`) operators
+ do not allocate variables outside stack
+ contain infinite loop
+ use nondeterministic values
+ simulate locking and unlocking set of locks in some manner

**Comment by mchalupa** [comment] 2020-01-21 13:16
`isValidPointer` query returns that all dereferences are ok, so it must be caused by the queries asking for leaks.

**Comment by mchalupa** [comment] 2020-01-21 13:21
In particular, it is in the `mayBeLeaked` query. There's only one rule using this query and if I remove this rule, no pointer is marked as unsafe.

**Closed** 2020-01-21 13:59 UTC
Labels: bug
