### ISSUE TITLE
Symbiotic uses system headers, but does not search all system locations

### ISSUE THREAD

**Issue by vlstill** [staticafi/symbiotic#70] opened 2017-09-13 13:39 UTC
```
$ ./install/bin/symbiotic --prp=memsafety mem_heap_bug01.c
cc: /usr/include/stdlib.h:33:10: fatal error: 'stddef.h' file not found
cc: 1 warning and 1 error generated.
RESULT: ERROR (Compiling source 'mem_heap_bug01.c' failed)
ERROR:  == FAILURE ==
Compiling source 'mem_heap_bug01.c' failed
```

running `echo | clang -v -x c -` shows that more there are three search locations on my installation (`/usr/local/include`, `/usr/bin/../lib/clang/4.0.1/include`, `/usr/include`) seems like symbiotic is using only `/usr/include`

the code is 

```{.c}
#include <stdlib.h>

int main() {
    int *array = malloc( 32 );
    if ( array == 0 ) {
        return 1;
    }
    array[ 4 ] = 16;
}
```

**Comment by mchalupa** [comment] 2017-09-21 13:55
Duplicate of #61

**Closed by mchalupa** 2017-09-21 13:55 UTC
